name: Matrix Jobs Demo
on: push
jobs:
    build:
        continue-on-error: true
        strategy:
            matrix:
                node-version: [12, 14, 16]
                operating-system: [ubuntu-latest, windows-latest]
                include:  #INCLUDES THIS BELOW AS A SINGLE COMBINATION
                    - node-version: 18
                      operating-system: ubuntu-latest 
                exclude: #EXCLUDES THIS BELOW AS A SINGLE COMBINATION
                    - node-version: 12
                      operating-system: windows-latest 
        runs-on: ${{ matrix.operating-system }}
        steps:
            - name: Get Code
              uses: actions/checkout@v4.1.1
            - name: Install NodeJS
              uses: actions/setup-node@v4.0.2
              with:
                node-version: ${{ matrix.node-version }}
            - name: Install Dependencies
              run: npm ci
            - name: Build Project
              run: npm run build