name: Reusable Workflows
on: 
    workflow_call:
        inputs:
            artifact-name:
                description: The name of the deployable artifact files
                required: false
                default: dist #default value if the value is not passed from the calling workflow
                type: string
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Download artifact
              uses: actions/download-artifact@v4.1.4
              with:
                name: ${{ inputs.artifact-name }}
            - name: List Files
              run: ls -ltr
            - name: Output Informaiton
              run: echo "Deploying & Uploading"